import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
// import { cn } from "../lib/utils"
import { Inter } from "next/font/google"
import { Sidebar } from "@/components/sidebar";
import { QueryProvider } from "@/components/react-query";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <QueryProvider>
          <Sidebar />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
